name : CALWIC_env
channels:
  - defaults 
  - conda-forge
dependencies:
  - spyder
  - numpy 
  - pandas 
  - matplotlib 
  - scipy
  - pip
  - pip: 
    - python-calamine
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - tabulate
    - requests
    - tqdm
