name: App

channels:
  - conda-forge
  - anaconda
  
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scipy
  - numpy
  - pandas
  - google-api-python-client
  - google-auth-oauthlib
  - tqdm
